Deliver cli 2.8
July, 15th 2013

New major improvements: execution contexts and faster python
transformation tools.

Major modifications:
* ExecutionContext class creation:
    - Shell ans ui controls improvements
    - NonBlockingKeyReceiver interface removal,
      NonBlockingIODevice::WaitForKeys removal
    - TelnetServer redesign
    - PwdShellContext sample
* Transformation / schema:
    - Systematic source generation
    - python scripts addition (more stable and faster): cli2cpp.py,
      cli2java.py, cli2help.py
    - XSL stylesheets, schema files and python scripts moved/added in a
      "tools" directory (backward compatibility with old XSL and schema
      paths is still provided)

Miscellaneous:
* Makefiles:
    - 'make' and 'make check' dissociation
    - Explicit message when dependencies should be regenerated
    - IfEquals, CheckDir, RemoveDir, CheckSh tool functions addition
* C++ improvements:
    - Input command lines growing limitation
    - 'explicit' constructors
    - Local protections addition in Cli::SetCli() and Menu::SetMenu()
      against memory leaks on multiple calls to SetCli()
    - Traces::SafeTrace() improvement, Traces::IsSafe() removal
    - ESCDELAY modification through set_escdelay() correction
* Java improvements:
    - Useless finalize() methods removal
    - deleteFromNative() gathered in NativeObject for any class
* Test improvements:
    - Addition of C++ tests/include headers, cli/test/TestTools.java for
      unit test routines factorization
    - Unit-test makefiles renamed with 'test_' prefix
    - test_tk.mak: Dual execution implementation: USE_STL=yes and
      USE_STL=no
    - Java test_no_res.mak unit-test addition
* Documentation:
    - doxygen: msc sequence charts addition, warnings removal
    - javadoc: package documentation

Bug fixes:
* Bug(major)! C++: 0x%08x to display pointer values causes a compile
    error (%p used instead)
* Bug(minor)! C++: Compilation errors with g++ 4.6.3
* Bug(minor)! C++: Crash in Traces::UnsetStream when streams are unset
    in the wrong order (trace output consistency improvement)
* Bug(minor)! C++: telnet unit test does not compile on certain
    configurations (#include <stdio.h> changed into #include <unistd.h>
    for close() definition)
* Bug(minor)! C++: OutputDevice::operator<<(void*) format improvements
    for better compatibility with 64 bits compilers
* Bug(minor)! C++: Build info when building in debug under Cygwin
    Info: resolving _ESCDELAY by linking to __imp__ESCDELAY
        (auto-import)
    Info: resolving _stdscr by linking to __imp__stdscr (auto-import)
    Info: resolving _LINES by linking to __imp__LINES (auto-import)
    Info: resolving _COLS by linking to __imp__COLS (auto-import)
* Bug(minor)! C++: _mkres.mak: bad force rule on $(CLI_CPP_LIB):
    dependencies always relink the applications
* Bug(minor)! C++: test_telnet "connect() failed" errors uner Linux
    (sleep added)
* Bug(major)! Java: "Java faile while executing command: 'cls'" =>
    well-known command control 'cls' missing in NativeMenu.cpp
* Bug(minor)! Java: java.lang.UnsatisfiedLinkError:
    __Native__getScreenInfo at
    cli.OutputDevice.__Native__getScreenInfo(Native Method) (visible
    when the getScreenInfo() is called from Java, fixed and checked
    with I/O devices unit test: java/build/make/io_device.mak,
    java/src/cli/test/TestIODevice.java)
* Bug(minor)! Java: Crash on Endl deletion with MenuRef reference set
    (visible when calling deprecated System.runFinalizersOnExit(true))
* Bug(minor)! Java: Native object references misfunctionning when
    declaring twice a same keyword in the same context (fixed and
    checked with test_no_res.mak)
* Bug(minor)! Java: Crash when calling deprecated
    System.runFinalizersOnExit(true) (token addition for static
    null/stdin/stdout/stderr devices)
* Bug(minor)! Java: Crash when calling deprecated
    System.runFinalizersOnExit(true) (no more finalization for
    TraceClass("CLI_JNI") main instance)
* Bug(minor)! Java: TestTelnet "Connection refused" errors under Linux
    java-6-openjdk (sleep added)
* Bug(minor)! cli2cpp.xsl/cli2java.xsl: accented character management in
    T_MkCppName/T_MkJavaName
* Bug(minor)! cli2java.xsl: Explicit java.lang/java.util package
    specification (avoid possible conflicts)
* Bug(minor)! cli2help.xsl: Forward tag commands do not appear in
    documentation (T_Recursion|CHECK_MENU fix)
* Bug(minor)! cli2help.xsl: Wrong default description for forward tag
    options.
* Bug(minor)! cli2help.xsl: Space missing in command names (due to
    xsltproc limitation?)

Rejected:
* Bug(minor)! cli2help.xsl: wrong number of options generated for (a|b)+
    patterns while (a|b)* works fine. cli2help.xsl, deprecated in
    CLI 2.9, will remain unfixed. Please use cli2help.py instead.